### ISSUE TITLE
This hands-on explores writing a code snippet to read the large data file data_file.txt using streams, and logging the sizes/length of chunks of data read, to the console.

### ISSUE THREAD

**Issue by DeepuGeorgeJacob** [frescoplaylab/Node-stream-handson#1]
`var fs = require("fs");
var stream = fs.createReadStream('Node-stream-handson/data_file.txt','utf8',{ highWaterMark: 60000 });
var data = ''
var dataLength = 0;
// using a readStream that we created already
stream
  .on('data', function (chunk) {
    dataLength += chunk.length;
    data+=chunk;
  })
  .on('end', function () {  // done
    console.log(data);
    console.log('The length was:', dataLength);
  });`

**Comment by DeepuGeorgeJacob** [comment]
This is the code which I tried and is not working

var fs = require("fs");
var stream = fs.createReadStream('Node-stream-handson/data_file.txt','utf8',{ highWaterMark: 60000 });
var data = ''
var dataLength = 0;
// using a readStream that we created already
stream
  .on('data', function (chunk) {
    dataLength += chunk.length;
    data+=chunk;
  })
  .on('end', function () {  // done
    console.log(data);
    console.log('The length was:', dataLength);
  });

**Comment by jcmartinezt95** [comment]
Did you solve this? Having same issues

**Comment by Horizon03** [comment]
did you solve this?

**Comment by premgct87** [comment]
I believe the issue is you are not logging the chunk length but logging only the total length.

console.log(chunk.length) - This will do

**Comment by ArpitBodana** [comment]
### **_**Solution -----**_-**

var fs = require("fs");
var stream = fs.createReadStream('Node-stream-handson/data_file.txt','utf8',{ highWaterMark: 60000 });
var data = ''

stream.on('data', function (chunk) {

console.log(chunk.length);

data+=chunk;
})
stream.on('end', function () { // done


});
